services:
  app:
    build: ./app
    container_name: login_service
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: ${DB_SSLMODE}
      PORT: ${PORT:-5000}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

  postgres:
    container_name: pgdb
    image: postgres:17.2
    environment:
      POSTGRES_DB: "login_service"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-d", "login_service"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migration:
    build: ./migration
    container_name: migration
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: ${DB_SSLMODE}
    depends_on:
      postgres:
        condition: service_healthy
