// Code generated by MockGen. DO NOT EDIT.
// Source: ./interfaces.go
//
// Generated by this command:
//
//	mockgen -source ./interfaces.go -destination ./mock/mocks.go
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	slog "log/slog"
	models "login/internals/models"
	session "login/pkg/session"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// DeleteUserService mocks base method.
func (m *MockUserService) DeleteUserService(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserService", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserService indicates an expected call of DeleteUserService.
func (mr *MockUserServiceMockRecorder) DeleteUserService(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserService", reflect.TypeOf((*MockUserService)(nil).DeleteUserService), ctx, id)
}

// GetAllUsers mocks base method.
func (m *MockUserService) GetAllUsers(ctx context.Context, limit, offset uint64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, limit, offset)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserServiceMockRecorder) GetAllUsers(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserService)(nil).GetAllUsers), ctx, limit, offset)
}

// GetUser mocks base method.
func (m *MockUserService) GetUser(ctx context.Context, id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserService)(nil).GetUser), ctx, id)
}

// Login mocks base method.
func (m *MockUserService) Login(ctx context.Context, param, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, param, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceMockRecorder) Login(ctx, param, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserService)(nil).Login), ctx, param, password)
}

// Registration mocks base method.
func (m *MockUserService) Registration(ctx context.Context, email, nickname, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Registration", ctx, email, nickname, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Registration indicates an expected call of Registration.
func (mr *MockUserServiceMockRecorder) Registration(ctx, email, nickname, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Registration", reflect.TypeOf((*MockUserService)(nil).Registration), ctx, email, nickname, password)
}

// UpdateEmail mocks base method.
func (m *MockUserService) UpdateEmail(ctx context.Context, id, newEmail string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, id, newEmail)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockUserServiceMockRecorder) UpdateEmail(ctx, id, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockUserService)(nil).UpdateEmail), ctx, id, newEmail)
}

// UpdateNickname mocks base method.
func (m *MockUserService) UpdateNickname(ctx context.Context, id, newNickname string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNickname", ctx, id, newNickname)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNickname indicates an expected call of UpdateNickname.
func (mr *MockUserServiceMockRecorder) UpdateNickname(ctx, id, newNickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNickname", reflect.TypeOf((*MockUserService)(nil).UpdateNickname), ctx, id, newNickname)
}

// UpdatePassword mocks base method.
func (m *MockUserService) UpdatePassword(ctx context.Context, id, oldPassword, newPassword string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, oldPassword, newPassword)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserServiceMockRecorder) UpdatePassword(ctx, id, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserService)(nil).UpdatePassword), ctx, id, oldPassword, newPassword)
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// AuthMiddleware mocks base method.
func (m *MockSessionManager) AuthMiddleware(log *slog.Logger) func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthMiddleware", log)
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// AuthMiddleware indicates an expected call of AuthMiddleware.
func (mr *MockSessionManagerMockRecorder) AuthMiddleware(log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthMiddleware", reflect.TypeOf((*MockSessionManager)(nil).AuthMiddleware), log)
}

// CreateAndSaveSession mocks base method.
func (m *MockSessionManager) CreateAndSaveSession(ctx context.Context, userId string) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAndSaveSession", ctx, userId)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAndSaveSession indicates an expected call of CreateAndSaveSession.
func (mr *MockSessionManagerMockRecorder) CreateAndSaveSession(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAndSaveSession", reflect.TypeOf((*MockSessionManager)(nil).CreateAndSaveSession), ctx, userId)
}

// DestroySession mocks base method.
func (m *MockSessionManager) DestroySession(ctx context.Context, sessionId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroySession", ctx, sessionId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroySession indicates an expected call of DestroySession.
func (mr *MockSessionManagerMockRecorder) DestroySession(ctx, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroySession", reflect.TypeOf((*MockSessionManager)(nil).DestroySession), ctx, sessionId)
}

// GetSessionCookie mocks base method.
func (m *MockSessionManager) GetSessionCookie(r *http.Request) *http.Cookie {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionCookie", r)
	ret0, _ := ret[0].(*http.Cookie)
	return ret0
}

// GetSessionCookie indicates an expected call of GetSessionCookie.
func (mr *MockSessionManagerMockRecorder) GetSessionCookie(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionCookie", reflect.TypeOf((*MockSessionManager)(nil).GetSessionCookie), r)
}

// GetSessionFromContext mocks base method.
func (m *MockSessionManager) GetSessionFromContext(r *http.Request) *session.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionFromContext", r)
	ret0, _ := ret[0].(*session.Session)
	return ret0
}

// GetSessionFromContext indicates an expected call of GetSessionFromContext.
func (mr *MockSessionManagerMockRecorder) GetSessionFromContext(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionFromContext", reflect.TypeOf((*MockSessionManager)(nil).GetSessionFromContext), r)
}

// LoadSession mocks base method.
func (m *MockSessionManager) LoadSession(ctx context.Context, userId string) (*session.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadSession", ctx, userId)
	ret0, _ := ret[0].(*session.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadSession indicates an expected call of LoadSession.
func (mr *MockSessionManagerMockRecorder) LoadSession(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadSession", reflect.TypeOf((*MockSessionManager)(nil).LoadSession), ctx, userId)
}

// SetDeadSessionCookie mocks base method.
func (m *MockSessionManager) SetDeadSessionCookie(w http.ResponseWriter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDeadSessionCookie", w)
}

// SetDeadSessionCookie indicates an expected call of SetDeadSessionCookie.
func (mr *MockSessionManagerMockRecorder) SetDeadSessionCookie(w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeadSessionCookie", reflect.TypeOf((*MockSessionManager)(nil).SetDeadSessionCookie), w)
}

// SetUpdatedSessionCookie mocks base method.
func (m *MockSessionManager) SetUpdatedSessionCookie(w http.ResponseWriter, sessionId string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUpdatedSessionCookie", w, sessionId)
}

// SetUpdatedSessionCookie indicates an expected call of SetUpdatedSessionCookie.
func (mr *MockSessionManagerMockRecorder) SetUpdatedSessionCookie(w, sessionId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUpdatedSessionCookie", reflect.TypeOf((*MockSessionManager)(nil).SetUpdatedSessionCookie), w, sessionId)
}
